import 'package:cloud_firestore/cloud_firestore.dart';

class UniversityValidator {
  static Future<bool> isWhiteListed(String? email) async {
    if (email == null) return Future.value(false);
    if (email.isEmpty) return Future.value(false);

    final emailParts = email.split('@');
    if (emailParts.length != 2) {
      return Future.value(false);
    }
    final emailDomain = emailParts[1].toLowerCase();

    bool isPreApproved = preApprovedDomains
        .any((x) => emailDomain.endsWith(x) || emailDomain.contains(".$x"));
    if (isPreApproved) return true;

    bool whitelisted = await _isWhitelistedDomain(emailDomain);
    return Future.value(whitelisted);
  }

  static Future<bool> _isWhitelistedDomain(String domain) async {
    var doc = await FirebaseFirestore.instance
        .collection('approvedOrgs')
        .doc(domain)
        .get();
    return Future.value(doc.exists);
  }

// deprecated... move this to a firebase collection
  static const List<String> preApprovedDomains = [
    "edu",
    "edu.au",
    "edu.gt",
    "edu.pe",
    "edu.co",
    "edu.ar",
    "edu.ve",
    "edu.gh",
    "edu.uy",
    "edu.ec",
    "edu.co",
    "edu.pe",
    "edu.ni",
    "ac.pa",
    "ac.tz",
    "ac.za",
    "ac.uk",
    "ac.jp",
    "ethz.ch",
    "unil.ch",
    "europa.eu",
    "ecb.org",
    "un.org",
    "wipro.org",
    "cern.org",
    "ideo.com",
    "ideo.org",
    "frogdesign.com",
    "mckinsey.com",
    "nngroup.com",
    "fjordnet.com",
    "bcg.com",
    "deloitte.com",
    "accenture.com",
    "veryday.com",
    "cambridge.org",
    "utoronto.ca",
    "kuleuven.be",
    "ubc.ca",
    "ku.dk",
    "lu.se",
    "kth.se",
    "dtu.dk",
    "uio.no",
    "helsinki.fi",
    "aalto.fi",
    "chalmers.se",
    "uu.se",
    "su.se",
    "au.dk",
    "gu.se",
    "uib.no",
    "utu.fi",
    "sdu.dk",
    "aau.dk",
    "liu.se",
    "jyu.fi",
    "umu.se",
    "ntnu.no",
    "unam.mx",
    "ucm.es",
    "uv.es",
    "unirioja.es",
    "uba.ar",
    "tec.mx",
    "uchile.cl",
    "ugr.es",
    "us.es",
    "uab.cat",
    "ehu.es",
    "upv.es",
    "upm.es",
    "edu.co",
    "ua.es",
    "um.es",
    "usal.es",
    "udg.mx",
    "uc.cl",
    "uam.es",
    "uc3m.es",
    "unizar.es",
    "unav.es",
    "uva.es",
    "uji.es",
    "uma.es",
    "uanl.mx",
    "ac.cr",
    "uah.es",
    "ipn.mx",
    "uv.mx",
    "uclm.es",
    "uvigo.es",
    "edu.co",
    "edu.ar",
    "uniovi.es",
    "usc.es",
    "uib.es",
    "ull.es",
    "uaemex.mx",
    "umh.es",
    "ujaen.es",
    "uca.es",
    "uco.es",
    "unican.es",
    "uam.mx",
    "udc.es",
    "ulpgc.es",
    "unex.es",
    "ual.es",
    "urjc.es",
    "udla.mx",
    "deusto.es",
    "urv.cat",
    "unileon.es",
    "udec.cl",
    "edu.mx",
    "buap.mx",
    "edu.hn",
    "upo.es",
    "udL.cat",
    "ucv.ve",
    "unavarra.es",
    "uach.cl",
    "uspceu.com",
    "upct.es",
    "usm.cl",
    "pucv.cl",
    "iteso.mx",
    "edu.sv",
    "ibero.mx",
    "uGto.mx",
    "uson.mx",
    "inacap.cl",
    "usach.cl",
    "ubu.es",
    "anahuac.mx",
    "colmex.mx",
    "uabc.mx",
    "itam.mx",
    "uimp.es",
    "nebrija.com",
    "uai.cl",
    "uaa.mx",
    "umich.mx",
    "ucol.mx",
    "edu.ec",
    "usb.ve",
    "udp.cl",
    "udd.cl",
    "uh.cu",
    "utalca.cl",
    "edu.ec",
    "uchceu.es",
    "una.py",
    "uvic.cat",
    "edu.ar",
    "uacj.mx",
    "uaq.mx",
    "unia.es",
    "ufrontera.cl",
    "uic.es",
    "uemc.es",
    "tecmilenio.mx",
    "uss.cl",
    "uaslp.mx",
    "uaem.mx",
    "uach.mx",
    "ufV.es",
    "ucv.es",
  ];
}
